import mysql.connector as kb
x=kb.connect(host="localhost",user="root",passwd="cs",charset="utf8",database="kinshuk")
crsr=x.cursor()
#crsr.execute("create table books(Title varchar(20),ISBN bigint)")
title=input("Enter book title : ")
ISBN=int(input("Enter book's ISBN : "))
g="insert into books values('{}',{})".format(title,ISBN)
crsr.execute(g)
x.commit()
x.close()
